# Num-Ex 예제
## 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [2]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
data2 =[[1,2,3],[4,5,6],[7,8,9]]
a2 = np.array(data2)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a1.dtype

dtype('int32')

In [12]:
a2.dtype

dtype('int32')

In [13]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

# 범위를 지정해 배열 생성

1. arr_obj = np.arange([start, ] stop[, step])
 - start부터 stop 전까지 step만큼 더해 배열을 생성
 - start 디폴트는 0
 - step 디폴트는 1
 

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
a1 = np.arange(1, 10)
a1.shape

(9,)

In [29]:
data2 =[[1,2,3],[4,5,6],[7,8,9]]
a2 = np.array(data2)
a2.shape

(3, 3)

#  범위를 지정해 배열 생성
1. reshape(m, n)
 - 배열의 차원 조정
 - m x n 행태로 변경
 - 데이터의 개수가 맞아야 함

In [30]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [38]:
b2 = np.arange(5)
b2.shape

(5,)

# 범위를 지정해 배열 생성
1. arr_obj = np.linspace(start, stop[, num])
 - start부터 stop까지(포함) num개의 NumPy 배열 생성
 - num 디폴트 값은 1
 - 간격 일정하게 해서 범위 안의 숫자 뽑아내서 배열 생성!

In [41]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

# 특별한 형태의 배열 생성
- arr_zero_n = np.zeros(n)
  - 엘리먼트 0의 값을 n개 가지는 배열 생성
- arr_zero_mxn = np.zeros((m,n))
  - 원소가 0인 배열 생성
- arr_one_n = np.ones(n)
  - 원소를 1로 채워라
- arr_one_mxn = np.ones((m,n))
  - 원소가 1인 배열 생성

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## RGB로 나타냄

# 특별한 형태의 배열 생성
1. arr_I = np.eye(n)
 - n x n 단위 행렬 생성

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 배열의 데이터 타입 변환 
1. 배열의 데이터 타입 기호 
 - b : 불 
 - i : 부호가 있는 정수 
 - u : 부호가 없는 정수 
 - f : 실수 
 - c : 복소수 
 - M : 날짜 
 - O : 파이썬 객체 
 - S 혹은 a : 바이트 배열 
 - U : 유니코드 
2. 데이터 타입의 숫자 
 - 비트 수 혹은 바이트 수 
  - 예
  - 'U8' : 8비트 유니코드 
  - 'i32' : 32비트 부호 있는 정수

- arr_obj = np.astype(타입)
 - 배열을 지정한 타입으로 변환

In [61]:
np.array(['1.5', '0.62'])

array(['1.5', '0.62'], dtype='<U4')

In [54]:
str_a1 = np.array(['1.456', '0.123'])
num_a1 = str_a1.astype(float)
num_a1

array([1.456, 0.123])

In [52]:
str_a1.dtype

dtype('<U5')

In [53]:
num_a1.dtype

dtype('<U5')

In [55]:
str_a2 = np.array(['1','2'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 2])

In [56]:
str_a2.dtype

dtype('<U1')

In [57]:
num_a2.dtype

dtype('int32')

# 난수 배열의 생성
- np.random.seed(시드값)
 - 난수 생성 시드값 설정
 - 시드값 기준으로 지정하면 동일한 패턴으로 나옴!
- rand_num = np.random.rand()
 - [0. 1) 사이의 실수 난수 생성
- rand_num = np.random.rand([d0, d1, …, dn])
 - 지정한 차원의 배열 생성
 - [0. 1) 사이의 실수 난수로 채움
- rand_num = np.random.randn([d0, d1, …, dn])
 - 지정한 차원의 배열 생성
 - 가우시안 표준 정규 분포를 따르는 실수 난수 채움
 - 평균 0, 0 주변 +,-
 - -1에서 1의 숫자 분포
- rand_num = np.random.randint([low,] high, [,size])
 - [low, high)사이의 정수 난수를 갖는 배열 생성
 - 정수 하나 뽑을 때
 - size는 배열의 크기
  - 튜플로 지정 (d0, d1, … , dn)
- low의 디폴트 값은 0

In [62]:
np.random.rand(2,3)

array([[0.04922377, 0.50443003, 0.36822008],
       [0.00627275, 0.36979456, 0.38649163]])

In [63]:
np.random.rand()

0.6675824271127531

In [64]:
np.random.rand(2,3,4)

array([[[0.74997287, 0.14692522, 0.87846555, 0.44975655],
        [0.37716888, 0.06714932, 0.40264027, 0.73406686],
        [0.54115652, 0.95448122, 0.49164713, 0.44236482]],

       [[0.97471852, 0.74804795, 0.56015438, 0.98687293],
        [0.305201  , 0.54139548, 0.33065698, 0.87963547],
        [0.30868416, 0.6504062 , 0.04555421, 0.04802128]]])

In [65]:
np.random.randint(10,size=(3,4))

array([[5, 3, 8, 7],
       [8, 2, 5, 3],
       [7, 8, 8, 0]])

In [66]:
np.random.randint(1,30)

3

## 기본 연산

In [67]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
arr1 + arr2

array([11, 22, 33, 44])

In [68]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [70]:
arr1 * 2

array([20, 40, 60, 80])

In [71]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [72]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [73]:
arr1 / arr2

array([10., 10., 10., 10.])

In [74]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [75]:
arr1 > 20

array([False, False,  True,  True])

## 통계를 위한 연산 

In [76]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [77]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [78]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [79]:
[arr3.min(), arr3.max()]

[0, 4]

 ## 배열의 인덱싱
- 배열명[위치]
 - 배열명[[위치1, 위치2, …, 위치n]]
- 해당 차원의 여러 원소 선택
 - 배열명[행_위치, 열_위치]
 - 배열명[ [행_위치1, 행_위치2, … , 행_위치n],
      - [열_위치1, 열_위치2, … , 열_위치n]]
    - 2차원 배열의 여러 원소를 선택
- 배열명[조건식]
 - 해당 조건식을 만족하는 원소만 선택된 배열# 

In [80]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [81]:
a1[0]

0

In [82]:
a1[4]

40

In [84]:
a1[[1,2,4]]

array([10, 20, 40])

In [86]:
a1.dtype

dtype('int32')

In [89]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [90]:
a2[0,2]

30

In [91]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [92]:
a2[1]

array([40, 50, 60])

In [94]:
a2[1] = 0
a2

array([[10, 20, 30],
       [ 0,  0,  0],
       [70, 80, 95]])

In [95]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [96]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [97]:
a2[[0,2], [0,1]]

array([10, 80])

In [98]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [99]:
a[(a%2)==0]

array([2, 4, 6])

## 배열의 슬라이싱
- 배열[시작_위치:끝_위치]
 - 시작_위치 ~ 끝_위치-1 범위의 슬라이싱
 -  시작_위치 생략시 0
 - 끝 위치 포함 안 된다!
 - 끝_위치 생략시 배열의 끝
- 배열[행시작_위치:행끝_위치, 열시작_위치:열끝_위치]
 - 2차원의 슬라이싱

In [100]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [101]:
b1[:]

array([ 0, 10, 20, 30, 40, 50])

In [102]:
b1[2:]

array([20, 30, 40, 50])

In [103]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [105]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

- 크롭

In [107]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [108]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [109]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [113]:
b2[:3][1:]

array([[40, 50, 60],
       [70, 80, 90]])

In [114]:
b2[1][0:2]

array([40, 50])

In [115]:
np.array([1,2])

array([1, 2])